### ISSUE TITLE
Compiling Project: make "recipe for target" error

### ISSUE THREAD

**Issue by 01000001-086** [kecsap/tensorflow_cpp_packaging#1]
### System information
Raspberry Pi 3 running a clean install of latest Raspbian (version November 2017)
and installed [tensorflow-cpp-rpi_1.6.0.git20180309.68a478d6c0.ppa1_armhf.deb](https://github.com/kecsap/tensorflow_cpp_packaging/releases)

### Problem
You have been a big help in my issue on [Raspberry Pi 3 C++ compiling issue #17618](https://github.com/tensorflow/tensorflow/issues/17618)

Now, I am trying to compile a new project using your 
"tensorflow-cpp-rpi_1.6.0.git20180309.68a478d6c0.ppa1_armhf.deb"
However when I ran the command "cmake" using my CMakeLists.txt below, I ran to an error.
```
CMAKE_MINIMUM_REQUIRED(VERSION 3.0)

PROJECT(ROBOCON)

SET(CMAKE_CXX_STANDARD 11)

# Find tensorflow-cpp
FIND_PACKAGE(TensorFlowCpp REQUIRED PATHS /usr/lib/cmake/tensorflow-cpp)

# Add the tensorflow-cpp paths to the include directories
INCLUDE_DIRECTORIES(${TENSORFLOWCPP_INCLUDE_DIRS})

# Add a target with your inference codes
ADD_EXECUTABLE(TFMinstCpp1 TFMinstCpp1.cpp)

# Link your application against the shared Tensorflow C++ library
TARGET_LINK_LIBRARIES(TFMinstCpp1 ${TENSORFLOWCPP_LIBRARIES} -lz)
```

Have I written custom code: Yes
OS Platform and Distribution : Raspbian (version November 2017)
TensorFlow installed from : tensorflow-cpp-rpi_1.6.0.git20180309.68a478d6c0.ppa1_armhf.deb
TensorFlow version: 1.6.0
Bazel version: N/A
CUDA/cuDNN version : N/A
GPU model and memory: N/A

### Logs
```
CMakeFiles/TFMinstCpp1.dir/build.make:62: recipe for target 'CMakeFiles/TFMinstCpp1.dir/TFMinstCpp1.cpp.o' failed
make[2]: *** [CMakeFiles/TFMinstCpp1.dir/TFMinstCpp1.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/TFMinstCpp1.dir/all' failed
make[1]: *** [CMakeFiles/TFMinstCpp1.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
I have attached the full error log output:
[tf_log.txt](https://github.com/kecsap/tensorflow_cpp_packaging/files/1833604/tf_log.txt)

I hope that you could still help me.

**Comment by kecsap** [comment]
Please make the log file with "make VERBOSE=1" and attach that here.

**Comment by kecsap** [comment]
Sorry, I was wrong in my previous comment, I have deleted. There is no tensorflow::ParseFlags in the Tensorflow API, maybe there was at some point, but it was removed. The docs are wrong in command_line_flags.h.

**Comment by kecsap** [comment]
I close this issue now. Feel free to reopen if you still have some problem
