### ISSUE TITLE
symbol _ZN10tensorflow30_ConfigProto_default_instance_E version tensorflow not defined in file libtensorflow_cc.so with link time reference

### ISSUE THREAD

**Issue by andres0820m** [kecsap/tensorflow_cpp_packaging#13]
hi i'm triying to use this share librarie, I'm using the .deb version and i got this error when i tried to run the program symbol _ZN10tensorflow30_ConfigProto_default_instance_E version tensorflow not defined in file libtensorflow_cc.so with link time reference any help ? the program works with my own compilation of tensorflow

**Comment by kecsap** [comment]
How do you compile your program? With CMake or custom Makefile, other build system or just manually in command line?

**Comment by andres0820m** [comment]
with cMake here is my cmake  
cmake_minimum_required(VERSION 2.8)
set(CMAKE_CXX_STANDARD 11)
project(comunication)
find_package( OpenCV REQUIRED)
# Find tensorflow-cpp
FIND_PACKAGE(TensorFlowCpp REQUIRED PATHS /usr/lib/cmake/tensorflow-cpp)
# Add the tensorflow-cpp paths to the include directories
INCLUDE_DIRECTORIES(${TENSORFLOWCPP_INCLUDE_DIRS})

file(GLOB SOURCES
       ./darknet/src/option_list.h
       ./darknet/src/option_list.c
       ./darknet/src/utils.h
       ./darknet/src/utils.h
       ./darknet/src/list.h
       ./darknet/src/list.c
       ./src/Detection.cpp
       ./src/Detection.hpp
       ./src/Tracker.cpp
       ./src/Tracker.hpp
       ./src/Results.cpp
       ./src/Results.hpp
       ./src/TrackIdentifiers.cpp
       ./src/TrackIdentifiers.hpp
       ./src/utils.cpp
       ./src/utils.hpp
       ./src/Constants.hpp
       ./src/Track.cpp
       ./src/Track.hpp
       ./src/DetectionCluster.cpp
       ./src/DetectionCluster.hpp
       ./src/Hungarian.cpp
       ./src/Hungarian.hpp
       ./src/Sorter.hpp
       ./src/Sorter.cpp)
########################################################################
#Add definitions
add_definitions ( -D SHOW_DEBUG=0 )
add_definitions ( -D PRINT_DEBUG=1 )
add_definitions ( -D PRINT_DEBUG_FILE=1 )
########################################################################
#Create the executable
add_library(darknet SHARED IMPORTED)
set(darknet_root "${CMAKE_CURRENT_SOURCE_DIR}/darknet")
set_target_properties(darknet PROPERTIES
       INTERFACE_INCLUDE_DIRECTORIES "${darknet_root}/src;${darknet_root}/include"
       IMPORTED_LOCATION "${darknet_root}/libdarknet.so"
       )
######################################################################## tf

########################################################################
add_executable(classifier classifier.cpp ${SOURCES} src/lstm.cpp src/lstm.hpp)

set_target_properties(classifier PROPERTIES
       CXX_STANDARD_REQUIRED ON
       CXX_STANDARD 11
       )
set(DCMAKE_BUILD_TYPE Release)

target_link_libraries( classifier
       PRIVATE ${OpenCV_LIBS}
       PRIVATE darknet
       ${TENSORFLOWCPP_LIBRARIES}
       )

**Comment by andres0820m** [comment]
> How do you compile your program? With CMake or custom Makefile, other build system or just manually in command line?

with CMake ,here is my CMake file 

cmake_minimum_required(VERSION 2.8)
set(CMAKE_CXX_STANDARD 11)
project(comunication)
find_package( OpenCV REQUIRED)
FIND_PACKAGE(TensorFlowCpp REQUIRED PATHS /usr/lib/cmake/tensorflow-cpp)

INCLUDE_DIRECTORIES(${TENSORFLOWCPP_INCLUDE_DIRS})

file(GLOB SOURCES
       ./darknet/src/option_list.h
       ./darknet/src/option_list.c
       ./darknet/src/utils.h
       ./darknet/src/utils.h
       ./darknet/src/list.h
       ./darknet/src/list.c
       ./src/Detection.cpp
       ./src/Detection.hpp
       ./src/Tracker.cpp
       ./src/Tracker.hpp
       ./src/Results.cpp
       ./src/Results.hpp
       ./src/TrackIdentifiers.cpp
       ./src/TrackIdentifiers.hpp
       ./src/utils.cpp
       ./src/utils.hpp
       ./src/Constants.hpp
       ./src/Track.cpp
       ./src/Track.hpp
       ./src/DetectionCluster.cpp
       ./src/DetectionCluster.hpp
       ./src/Hungarian.cpp
       ./src/Hungarian.hpp
       ./src/Sorter.hpp
       ./src/Sorter.cpp)
########################################################################
#Add definitions
add_definitions ( -D SHOW_DEBUG=0 )
add_definitions ( -D PRINT_DEBUG=1 )
add_definitions ( -D PRINT_DEBUG_FILE=1 )
########################################################################
#Create the executable
add_library(darknet SHARED IMPORTED)
set(darknet_root "${CMAKE_CURRENT_SOURCE_DIR}/darknet")
set_target_properties(darknet PROPERTIES
       INTERFACE_INCLUDE_DIRECTORIES "${darknet_root}/src;${darknet_root}/include"
       IMPORTED_LOCATION "${darknet_root}/libdarknet.so"
       )
######################################################################## tf

########################################################################
add_executable(classifier classifier.cpp ${SOURCES} src/lstm.cpp src/lstm.hpp)

set_target_properties(classifier PROPERTIES
       CXX_STANDARD_REQUIRED ON
       CXX_STANDARD 11
       )
set(DCMAKE_BUILD_TYPE Release)

target_link_libraries( classifier
       PRIVATE ${OpenCV_LIBS}
       PRIVATE darknet
       ${TENSORFLOWCPP_LIBRARIES}
       )

**Comment by kecsap** [comment]
Does the linking step fail? If so, can you compile this step with "make VERBOSE=1" and post here the results? Which deb file did you download?

**Comment by andres0820m** [comment]
> Does the linking step fail? If so, can you compile this step with "make VERBOSE=1" and post here the results? Which deb file did you download?
whit the two of them and i got the same result, the program compiles well, but when I try to run it is when i got the error, here is the verbose output of the make operation 

make VERBOSE=1
/usr/bin/cmake -H/home/amejia/CLionProjects/ltsm_cpp_andres -B/home/amejia/CLionProjects/ltsm_cpp_andres/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/amejia/CLionProjects/ltsm_cpp_andres/build/CMakeFiles /home/amejia/CLionProjects/ltsm_cpp_andres/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: se entra en el directorio '/home/amejia/CLionProjects/ltsm_cpp_andres/build'
make -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/depend
make[2]: se entra en el directorio '/home/amejia/CLionProjects/ltsm_cpp_andres/build'
cd /home/amejia/CLionProjects/ltsm_cpp_andres/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/amejia/CLionProjects/ltsm_cpp_andres /home/amejia/CLionProjects/ltsm_cpp_andres /home/amejia/CLionProjects/ltsm_cpp_andres/build /home/amejia/CLionProjects/ltsm_cpp_andres/build /home/amejia/CLionProjects/ltsm_cpp_andres/build/CMakeFiles/classifier.dir/DependInfo.cmake --color=
Dependee "/home/amejia/CLionProjects/ltsm_cpp_andres/build/CMakeFiles/classifier.dir/DependInfo.cmake" is newer than depender "/home/amejia/CLionProjects/ltsm_cpp_andres/build/CMakeFiles/classifier.dir/depend.internal".
Dependee "/home/amejia/CLionProjects/ltsm_cpp_andres/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/amejia/CLionProjects/ltsm_cpp_andres/build/CMakeFiles/classifier.dir/depend.internal".
Scanning dependencies of target classifier
make[2]: se sale del directorio '/home/amejia/CLionProjects/ltsm_cpp_andres/build'
make -f CMakeFiles/classifier.dir/build.make CMakeFiles/classifier.dir/build
make[2]: se entra en el directorio '/home/amejia/CLionProjects/ltsm_cpp_andres/build'
[  7%] Building CXX object CMakeFiles/classifier.dir/classifier.cpp.o
/usr/bin/c++   -I/usr/include/tensorflow-cpp -I/usr/include/tensorflow-cpp/external/nsync/public -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/include  -D SHOW_DEBUG=0 -D PRINT_DEBUG=1 -D PRINT_DEBUG_FILE=1 -std=gnu++11 -o CMakeFiles/classifier.dir/classifier.cpp.o -c /home/amejia/CLionProjects/ltsm_cpp_andres/classifier.cpp
[ 14%] Building C object CMakeFiles/classifier.dir/darknet/src/option_list.c.o
/usr/bin/cc  -I/usr/include/tensorflow-cpp -I/usr/include/tensorflow-cpp/external/nsync/public -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/include  -D SHOW_DEBUG=0 -D PRINT_DEBUG=1 -D PRINT_DEBUG_FILE=1 -o CMakeFiles/classifier.dir/darknet/src/option_list.c.o   -c /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src/option_list.c
[ 21%] Building C object CMakeFiles/classifier.dir/darknet/src/list.c.o
/usr/bin/cc  -I/usr/include/tensorflow-cpp -I/usr/include/tensorflow-cpp/external/nsync/public -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/include  -D SHOW_DEBUG=0 -D PRINT_DEBUG=1 -D PRINT_DEBUG_FILE=1 -o CMakeFiles/classifier.dir/darknet/src/list.c.o   -c /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src/list.c
[ 28%] Building CXX object CMakeFiles/classifier.dir/src/Detection.cpp.o
/usr/bin/c++   -I/usr/include/tensorflow-cpp -I/usr/include/tensorflow-cpp/external/nsync/public -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/include  -D SHOW_DEBUG=0 -D PRINT_DEBUG=1 -D PRINT_DEBUG_FILE=1 -std=gnu++11 -o CMakeFiles/classifier.dir/src/Detection.cpp.o -c /home/amejia/CLionProjects/ltsm_cpp_andres/src/Detection.cpp
[ 35%] Building CXX object CMakeFiles/classifier.dir/src/Tracker.cpp.o
/usr/bin/c++   -I/usr/include/tensorflow-cpp -I/usr/include/tensorflow-cpp/external/nsync/public -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/include  -D SHOW_DEBUG=0 -D PRINT_DEBUG=1 -D PRINT_DEBUG_FILE=1 -std=gnu++11 -o CMakeFiles/classifier.dir/src/Tracker.cpp.o -c /home/amejia/CLionProjects/ltsm_cpp_andres/src/Tracker.cpp
[ 42%] Building CXX object CMakeFiles/classifier.dir/src/Results.cpp.o
/usr/bin/c++   -I/usr/include/tensorflow-cpp -I/usr/include/tensorflow-cpp/external/nsync/public -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/include  -D SHOW_DEBUG=0 -D PRINT_DEBUG=1 -D PRINT_DEBUG_FILE=1 -std=gnu++11 -o CMakeFiles/classifier.dir/src/Results.cpp.o -c /home/amejia/CLionProjects/ltsm_cpp_andres/src/Results.cpp
[ 50%] Building CXX object CMakeFiles/classifier.dir/src/TrackIdentifiers.cpp.o
/usr/bin/c++   -I/usr/include/tensorflow-cpp -I/usr/include/tensorflow-cpp/external/nsync/public -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/include  -D SHOW_DEBUG=0 -D PRINT_DEBUG=1 -D PRINT_DEBUG_FILE=1 -std=gnu++11 -o CMakeFiles/classifier.dir/src/TrackIdentifiers.cpp.o -c /home/amejia/CLionProjects/ltsm_cpp_andres/src/TrackIdentifiers.cpp
[ 57%] Building CXX object CMakeFiles/classifier.dir/src/utils.cpp.o
/usr/bin/c++   -I/usr/include/tensorflow-cpp -I/usr/include/tensorflow-cpp/external/nsync/public -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/include  -D SHOW_DEBUG=0 -D PRINT_DEBUG=1 -D PRINT_DEBUG_FILE=1 -std=gnu++11 -o CMakeFiles/classifier.dir/src/utils.cpp.o -c /home/amejia/CLionProjects/ltsm_cpp_andres/src/utils.cpp
[ 64%] Building CXX object CMakeFiles/classifier.dir/src/Track.cpp.o
/usr/bin/c++   -I/usr/include/tensorflow-cpp -I/usr/include/tensorflow-cpp/external/nsync/public -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/include  -D SHOW_DEBUG=0 -D PRINT_DEBUG=1 -D PRINT_DEBUG_FILE=1 -std=gnu++11 -o CMakeFiles/classifier.dir/src/Track.cpp.o -c /home/amejia/CLionProjects/ltsm_cpp_andres/src/Track.cpp
[ 71%] Building CXX object CMakeFiles/classifier.dir/src/DetectionCluster.cpp.o
/usr/bin/c++   -I/usr/include/tensorflow-cpp -I/usr/include/tensorflow-cpp/external/nsync/public -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/include  -D SHOW_DEBUG=0 -D PRINT_DEBUG=1 -D PRINT_DEBUG_FILE=1 -std=gnu++11 -o CMakeFiles/classifier.dir/src/DetectionCluster.cpp.o -c /home/amejia/CLionProjects/ltsm_cpp_andres/src/DetectionCluster.cpp
[ 78%] Building CXX object CMakeFiles/classifier.dir/src/Hungarian.cpp.o
/usr/bin/c++   -I/usr/include/tensorflow-cpp -I/usr/include/tensorflow-cpp/external/nsync/public -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/include  -D SHOW_DEBUG=0 -D PRINT_DEBUG=1 -D PRINT_DEBUG_FILE=1 -std=gnu++11 -o CMakeFiles/classifier.dir/src/Hungarian.cpp.o -c /home/amejia/CLionProjects/ltsm_cpp_andres/src/Hungarian.cpp
[ 85%] Building CXX object CMakeFiles/classifier.dir/src/Sorter.cpp.o
/usr/bin/c++   -I/usr/include/tensorflow-cpp -I/usr/include/tensorflow-cpp/external/nsync/public -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/include  -D SHOW_DEBUG=0 -D PRINT_DEBUG=1 -D PRINT_DEBUG_FILE=1 -std=gnu++11 -o CMakeFiles/classifier.dir/src/Sorter.cpp.o -c /home/amejia/CLionProjects/ltsm_cpp_andres/src/Sorter.cpp
[ 92%] Building CXX object CMakeFiles/classifier.dir/src/lstm.cpp.o
/usr/bin/c++   -I/usr/include/tensorflow-cpp -I/usr/include/tensorflow-cpp/external/nsync/public -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/src -isystem /home/amejia/CLionProjects/ltsm_cpp_andres/darknet/include  -D SHOW_DEBUG=0 -D PRINT_DEBUG=1 -D PRINT_DEBUG_FILE=1 -std=gnu++11 -o CMakeFiles/classifier.dir/src/lstm.cpp.o -c /home/amejia/CLionProjects/ltsm_cpp_andres/src/lstm.cpp
[100%] Linking CXX executable classifier
/usr/bin/cmake -E cmake_link_script CMakeFiles/classifier.dir/link.txt --verbose=1
/usr/bin/c++    -rdynamic CMakeFiles/classifier.dir/classifier.cpp.o CMakeFiles/classifier.dir/darknet/src/option_list.c.o CMakeFiles/classifier.dir/darknet/src/list.c.o CMakeFiles/classifier.dir/src/Detection.cpp.o CMakeFiles/classifier.dir/src/Tracker.cpp.o CMakeFiles/classifier.dir/src/Results.cpp.o CMakeFiles/classifier.dir/src/TrackIdentifiers.cpp.o CMakeFiles/classifier.dir/src/utils.cpp.o CMakeFiles/classifier.dir/src/Track.cpp.o CMakeFiles/classifier.dir/src/DetectionCluster.cpp.o CMakeFiles/classifier.dir/src/Hungarian.cpp.o CMakeFiles/classifier.dir/src/Sorter.cpp.o CMakeFiles/classifier.dir/src/lstm.cpp.o  -o classifier -Wl,-rpath,/usr/local/lib:/home/amejia/CLionProjects/ltsm_cpp_andres/darknet /usr/local/lib/libopencv_stitching.so.3.4.7 /usr/local/lib/libopencv_superres.so.3.4.7 /usr/local/lib/libopencv_videostab.so.3.4.7 /usr/local/lib/libopencv_aruco.so.3.4.7 /usr/local/lib/libopencv_bgsegm.so.3.4.7 /usr/local/lib/libopencv_bioinspired.so.3.4.7 /usr/local/lib/libopencv_ccalib.so.3.4.7 /usr/local/lib/libopencv_cvv.so.3.4.7 /usr/local/lib/libopencv_dnn_objdetect.so.3.4.7 /usr/local/lib/libopencv_dpm.so.3.4.7 /usr/local/lib/libopencv_face.so.3.4.7 /usr/local/lib/libopencv_freetype.so.3.4.7 /usr/local/lib/libopencv_fuzzy.so.3.4.7 /usr/local/lib/libopencv_hdf.so.3.4.7 /usr/local/lib/libopencv_hfs.so.3.4.7 /usr/local/lib/libopencv_img_hash.so.3.4.7 /usr/local/lib/libopencv_line_descriptor.so.3.4.7 /usr/local/lib/libopencv_optflow.so.3.4.7 /usr/local/lib/libopencv_reg.so.3.4.7 /usr/local/lib/libopencv_rgbd.so.3.4.7 /usr/local/lib/libopencv_saliency.so.3.4.7 /usr/local/lib/libopencv_stereo.so.3.4.7 /usr/local/lib/libopencv_structured_light.so.3.4.7 /usr/local/lib/libopencv_surface_matching.so.3.4.7 /usr/local/lib/libopencv_tracking.so.3.4.7 /usr/local/lib/libopencv_xfeatures2d.so.3.4.7 /usr/local/lib/libopencv_ximgproc.so.3.4.7 /usr/local/lib/libopencv_xobjdetect.so.3.4.7 /usr/local/lib/libopencv_xphoto.so.3.4.7 ../darknet/libdarknet.so -Wl,-rpath=/usr/lib/tensorflow-cpp -L/usr/lib/tensorflow-cpp -ltensorflow_cc -Wl,--no-as-needed /usr/lib/tensorflow-cpp/libprotobuf.a -Wl,--as-needed /usr/local/lib/libopencv_shape.so.3.4.7 /usr/local/lib/libopencv_highgui.so.3.4.7 /usr/local/lib/libopencv_videoio.so.3.4.7 /usr/local/lib/libopencv_phase_unwrapping.so.3.4.7 /usr/local/lib/libopencv_video.so.3.4.7 /usr/local/lib/libopencv_datasets.so.3.4.7 /usr/local/lib/libopencv_plot.so.3.4.7 /usr/local/lib/libopencv_text.so.3.4.7 /usr/local/lib/libopencv_dnn.so.3.4.7 /usr/local/lib/libopencv_ml.so.3.4.7 /usr/local/lib/libopencv_imgcodecs.so.3.4.7 /usr/local/lib/libopencv_objdetect.so.3.4.7 /usr/local/lib/libopencv_calib3d.so.3.4.7 /usr/local/lib/libopencv_features2d.so.3.4.7 /usr/local/lib/libopencv_flann.so.3.4.7 /usr/local/lib/libopencv_photo.so.3.4.7 /usr/local/lib/libopencv_imgproc.so.3.4.7 /usr/local/lib/libopencv_core.so.3.4.7 
make[2]: se sale del directorio '/home/amejia/CLionProjects/ltsm_cpp_andres/build'
[100%] Built target classifier
make[1]: se sale del directorio '/home/amejia/CLionProjects/ltsm_cpp_andres/build'
/usr/bin/cmake -E cmake_progress_start /home/amejia/CLionProjects/ltsm_cpp_andres/build/CMakeFiles 0

**Comment by kecsap** [comment]
So do you receive an error message when you run the executable? I don't see any error message in the compilation log.
Which deb file did you download and install?

**Comment by andres0820m** [comment]
> So do you receive an error message when you run the executable? I don't see any error message in the compilation log.
> Which deb file did you download and install?

hi i already fix it, the solution was to add the route of the .so files at the end of the cmake file, but i have  new error, when the programs if going to run if showns libcublas.so.10.1 doesn't exist on the cuda folder, I fix it copying libcublas.so.10 from /usr/lib/x86.... to the actual cuda folder /usr/local/cuda10.1/lib64 and changing the name to libcublas.so.10.1 any guess on a more decent fix ??

**Comment by kecsap** [comment]
Cool!
The temporary solution to add CUDA path to the library path
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda10.1/lib64
````
Or to have it permanenti in the library paths, create a file in /etc/ld.so.conf.d/, e.g. /etc/ld.so.conf.d/cuda.conf, with this content:
```
/usr/local/cuda10.1/lib64
```
