### ISSUE TITLE
error: fakeroot debian/rules binary gave error exit status 2

### ISSUE THREAD

**Issue by houxy12** [kecsap/tensorflow_cpp_packaging#2]
Hello, I'm very appreciate that you can share your project. But I meet some problems when I compile the code.
In the fourth step,I met the problem:
Makefile:115: recipe for target 'install' failed
make[2]: *** [install] Error 1
make[2]: Leaving directory '/home/pi/tensorflow_cpp_packaging/packaging'
debian/rules:13: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/pi/tensorflow_cpp_packaging/packaging'
debian/rules:7: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
Can you give me some help? Thank you very much.

**Comment by kecsap** [comment]
Do you target Intel/AMD machine or Raspberry Pi?

I have just committed a change for the bleeding edge Tensorflow.
1. Please update this repo with "git pull" and try to build again.
2. If your build still does not work, I would need the log file from the compilation/packaging steps what you can get with nohup. For example the following commands:
nohup ./3_build_tensorflow_cpp_generic_x86_64.sh
nohup ./4_generate_generic_x86_64_package.sh
...will create a nohup.out file and add all log text into this file. Please attach that file here.
3. An other alternative way if you just download a ready-made debian package from the Release tab and you install it on your Debian/Ubuntu system.

**Comment by houxy12** [comment]
I build the code in raspberry,I'll try it another time,thank you.

**Comment by kecsap** [comment]
I close this issue now. Reopen if you still encounter some problem.
