### ISSUE TITLE
A question about how to use GPU when using C++ API with tensorflow?

### ISSUE THREAD

**Issue by xiaowenhe** [kecsap/tensorflow_cpp_packaging#3]
Hello,
       Thanks for your work! Following your code, I can use pure C++ API with tensorflow with CPU for detection.
       But I have a problem that how to use GPU when I use C++ API .

       My code like this:

#include <tensorflow/core/protobuf/meta_graph.pb.h>
#include <tensorflow/core/public/session.h>
#include <tensorflow/core/graph/default_device.h>
#include <tensorflow/core/graph/graph_def_builder.h>

tensorflow::GraphDef GraphDef;
tensorflow::Session* Session = nullptr;

1  void LoadGraph()
2  {
3          // Read in the protobuf graph we exported
4         tensorflow::Status Status;
5
6         Status = tensorflow::ReadBinaryProto(tensorflow::Env::Default(), "my_model.pb", &GraphDef);
7        if (!Status.ok())
8        {
9           printf("Error reading graph definition from %s: %s\n", "my_model.pb", Status.ToString().c_str());
10           return false;
11       }
12
13       Session = tensorflow::NewSession(tensorflow::SessionOptions());
14       if (Session == nullptr)
15      {
16           printf("Could not create Tensorflow session.\n");
17           return false;
18       }
19
20      graph::SetDefaultDevice("/device:GPU:0",&GraphDef); ///////// I add , for use GPU

21      // Add the graph to the session
22       Status = Session->Create(GraphDef);
23       if (!Status.ok())
24      {
25          printf("Error creating graph: %s\n", Status.ToString().c_str());
26          return false;
27      }
28 }

In the above code, the line 20 is I added for use GPU. But the code will be get an error. It will go into the line 25, that is say in line 23,   Status.ok() = false..

If I move the line 20 to the line 28,like 

#include <tensorflow/core/protobuf/meta_graph.pb.h>
#include <tensorflow/core/public/session.h>
#include <tensorflow/core/graph/default_device.h>
#include <tensorflow/core/graph/graph_def_builder.h>

tensorflow::GraphDef GraphDef;
tensorflow::Session* Session = nullptr;

1  void LoadGraph()
2  {
3          // Read in the protobuf graph we exported
4         tensorflow::Status Status;
5
6         Status = tensorflow::ReadBinaryProto(tensorflow::Env::Default(), "my_model.pb", &GraphDef);
7        if (!Status.ok())
8        {
9           printf("Error reading graph definition from %s: %s\n", "my_model.pb", Status.ToString().c_str());
10           return false;
11       }
12
13       Session = tensorflow::NewSession(tensorflow::SessionOptions());
14       if (Session == nullptr)
15      {
16           printf("Could not create Tensorflow session.\n");
17           return false;
18       }
19
20     

21      // Add the graph to the session
22       Status = Session->Create(GraphDef);
23       if (!Status.ok())
24      {
25          printf("Error creating graph: %s\n", Status.ToString().c_str());
26          return false;
27      }
28      graph::SetDefaultDevice("/device:GPU:0",&GraphDef); ///////// I add , for use GPU
29 }

The program can run ,but it use CPU. 

So can you tell me how to use GPU in the above code!

 Whether you know or not ,please write to me soon!   Thank you very much!

**Comment by kecsap** [comment]
Sorry, this project does not support GPU inference, only CPU. If you want GPU inference, use this Tensorflow inference project:

https://github.com/FloopCZ/tensorflow_cc

**Comment by xiaowenhe** [comment]
Sorry I only use the code you write in readme and not use your project，I use bazel compile the tensorflow as a libtensorflow_cc.so.   And then I use the above code and the libtensorflow_cc.so for detection.  Then I get the problems like above. I don not know how to deal with it.

**Comment by kecsap** [comment]
You can check this Tensorflow issue if it gives you any pointers what is wrong on your side:

https://github.com/tensorflow/tensorflow/issues/3126

**Comment by xiaowenhe** [comment]
OK,thank you!

**Comment by harendra247** [comment]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): jetpack 4.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):2.0.0
- Python version: 2.7
- Bazel version (if compiling from source):0.26.1
- GCC/Compiler version (if compiling from source):7.5
- CUDA/cuDNN version:10.0/7.6.3
- GPU model and memory: tegra tx2


**Describe the current behavior**
when I try running sample application it is crashing. With error logs as "CUDA runtime implicit initialization on GPU:0 failed. Status: unknown error"

**Describe the expected behavior**
it should start session

**Standalone code to reproduce the issue**
Sample Code 
```
#include <tensorflow/core/platform/env.h>
#include <tensorflow/core/public/session.h>
#include <iostream>
using namespace std;
using namespace tensorflow;

int main()
{
    Session* session;
    Status status = NewSession(SessionOptions(), &session);
    if (!status.ok()) {
        cout << status.ToString() << "\n";
    }
    session->Close();
    cout << "Session successfully created.\n";
}

```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.10)

project(test_hello)

set(TENSORFLOW_LIBRARIES tensorflow_cc protobuf)
add_executable(example example.cpp)
set(CUDA_NVCC_FLAGS
        ${CUDA_NVCC_FLAGS};
        -O3 -gencode arch=compute_30,code=sm_30;
        --std=c++11
        )
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Link the Tensorflow library.
# TensorFlow headers
include_directories("/usr/local/include/")
include_directories("/usr/local/include/tensorflow/")
include_directories("/usr/local/include/third-party/")
target_link_libraries(example "/usr/local/lib/libtensorflow_cc.so")

# You may also link cuda if it is available.
find_package(CUDA)
if(CUDA_FOUND)
  target_link_libraries(example ${CUDA_LIBRARIES})
endif()

```

**Other info / logs**

```
$ ./example 
2020-07-08 15:01:34.122381: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-08 15:01:34.127413: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:973] ARM64 does not support NUMA - returning NUMA node zero
2020-07-08 15:01:34.127566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA Tegra X2 major: 6 minor: 2 memoryClockRate(GHz): 1.3
pciBusID: 0000:00:00.0
2020-07-08 15:01:34.127608: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-07-08 15:01:34.127693: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:973] ARM64 does not support NUMA - returning NUMA node zero
2020-07-08 15:01:34.127815: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:973] ARM64 does not support NUMA - returning NUMA node zero
2020-07-08 15:01:34.127879: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
Internal: CUDA runtime implicit initialization on GPU:0 failed. Status: unknown error
Segmentation fault (core dumped)

```
