### ISSUE TITLE
ModuleNotFoundError keras_application

### ISSUE THREAD

**Issue by AhmedX6** [kecsap/tensorflow_cpp_packaging#5]
Hello,

I'm facing issue while b "make wheel for headers"
Got this error after whole build "**ModuleNotFoundError: No module named 'keras_applications'**"

I'm on WSL Ubuntu 18.04 on Windows 10.
I tried to pip install keras_application but still same result after rebuilding.

Please can I have some help ?

Thanks

**Comment by AhmedX6** [comment]
Think I solved this by doing "pip install keras"

But still "FAILED: Build did NOT complete successfully"

I do not see any errors on build, please can I have some help ?

**Comment by kecsap** [comment]
Did you notice that I provide prebuilt version?
https://github.com/kecsap/tensorflow_cpp_packaging/releases

I have no idea if the build can work on WSL Ubuntu 18.04, it was only tested on native Ubuntu system.

**Comment by AhmedX6** [comment]
It should be interesting to build it on WSL.
I have a "Failed build not complete successfully" anyway... But no error from Keras...
Will try to do the next commands anyway

**Comment by AhmedX6** [comment]
Hi,
Success make wheel for headers.
But 
 file INSTALL cannot find libnsync-tf.a 
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2

Any solution ?

**Comment by kecsap** [comment]
Closing since WSL build is not supported, but it can be worth a try to just install a debian package from the releases on WSL to see if it works.
