### ISSUE TITLE
No tensorflow/cc headers installed with latest 1.10 release package

### ISSUE THREAD

**Issue by TrevorCash** [kecsap/tensorflow_cpp_packaging#6]

**Comment by kecsap** [comment]
Which file is wrong in https://github.com/kecsap/tensorflow_cpp_packaging/releases?

**Comment by TrevorCash** [comment]
I downloaded tensorflow-cpp-generic_1.10.0.git20180810.56e4ea405d.ppa1_amd64.deb

https://github.com/kecsap/tensorflow_cpp_packaging/releases/download/Tensorflow_1.10.0fix1_git20180810_56e4ea40/tensorflow-cpp-generic_1.10.0.git20180810.56e4ea405d.ppa1_amd64.deb

**Comment by TrevorCash** [comment]
Im looking to use the includes such as:
```
#include "tensorflow/cc/client/client_session.h"
#include "tensorflow/cc/ops/standard_ops.h"
//etc
```

**Comment by kecsap** [comment]
Right, I will fix and upload a new version.

**Comment by kecsap** [comment]
I uploaded a new release with the missing C++ headers. Hopefully, it will work out-of-the-box. I use these packages only for inference.

**Comment by TrevorCash** [comment]
They work now!  Thanks for fixing

**Comment by kecsap** [comment]
Welcome!
